# Generated by Django 4.2.5 on 2023-12-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('FotoCliente', models.ImageField(upload_to='')),
                ('Datavenda', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='roupa',
            fields=[
                ('id_roupa', models.AutoField(primary_key=True, serialize=False)),
                ('FotoRoupa', models.ImageField(upload_to='')),
                ('Preco', models.FloatField()),
            ],
        ),
    ]
