# Generated by Django 4.2.5 on 2023-12-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='Cor',
            field=models.CharField(default='valor', max_length=15),
        ),
        migrations.AddField(
            model_name='roupa',
            name='Tamanho',
            field=models.CharField(default='valor', max_length=15),
        ),
    ]
