# Generated by Django 4.2.5 on 2023-12-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0002_roupa_cor_roupa_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='FotoCliente',
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='FotoRoupa',
        ),
        migrations.AlterField(
            model_name='roupa',
            name='Cor',
            field=models.CharField(default='qualquer', max_length=15),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='Tamanho',
            field=models.CharField(default='P', max_length=15),
        ),
    ]
