# Generated by Django 5.0 on 2023-12-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0003_remove_cliente_fotocliente_remove_roupa_fotoroupa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_cliente',
            new_name='idcliente',
        ),
        migrations.RenameField(
            model_name='roupa',
            old_name='id_roupa',
            new_name='idroupa',
        ),
    ]
