# Generated by Django 5.0 on 2023-12-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0004_rename_id_cliente_cliente_idcliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Datavenda',
        ),
        migrations.AlterField(
            model_name='roupa',
            name='Cor',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='Preco',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='Tamanho',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='DataVenda',
            field=models.DateField(null=True),
        ),
    ]
