# Generated by Django 5.0 on 2024-01-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0005_rename_nome_cliente_nome_remove_cliente_datavenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='LinkTel',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
