# Generated by Django 5.0 on 2024-01-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0006_cliente_linktel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='Tamanho',
            field=models.BooleanField(null=True),
        ),
    ]
