# Generated by Django 5.0 on 2024-01-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0007_alter_roupa_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='Tamanho',
        ),
        migrations.AddField(
            model_name='roupa',
            name='tamanhos',
            field=models.ManyToManyField(to='projetoapp.tamanho'),
        ),
    ]
