# Generated by Django 5.0 on 2024-01-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0009_roupa_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='roupa_comprada',
            field=models.ManyToManyField(blank=True, to='projetoapp.roupa'),
        ),
    ]
