# Generated by Django 5.0 on 2024-01-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0012_alter_roupa_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roupa',
            name='tamanhos',
        ),
        migrations.AddField(
            model_name='roupa',
            name='Tamanho',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
