# Generated by Django 5.0 on 2024-01-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0013_remove_roupa_tamanhos_roupa_tamanho_delete_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='DataVenda',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='roupa_comprada',
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('idvenda', models.AutoField(primary_key=True, serialize=False)),
                ('DataVenda', models.DateField(null=True)),
                ('cliente_comprou', models.ManyToManyField(blank=True, to='projetoapp.cliente')),
                ('roupa_comprada', models.ManyToManyField(blank=True, to='projetoapp.roupa')),
            ],
        ),
    ]
