# Generated by Django 5.0 on 2024-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0014_remove_cliente_datavenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='FotoRoupa',
            field=models.ImageField(null=True, upload_to='projetoapp/images/%Y/%m/%d/'),
        ),
    ]
