# Generated by Django 5.0 on 2024-01-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0015_roupa_fotoroupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='FotoRoupa',
            field=models.ImageField(blank=True, null=True, upload_to='fotosroupas/'),
        ),
    ]
