# Generated by Django 5.0 on 2024-01-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0017_remove_venda_cliente_comprou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='nomebrecho',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
