# Generated by Django 5.0 on 2024-02-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0020_alter_roupa_fotoroupa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='LinkTel',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Nome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='PrimeiroNome',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='SegundoNome',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Tel',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
