# Generated by Django 4.2.11 on 2024-07-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0021_remove_cliente_linktel_remove_cliente_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='idcliente',
            new_name='idCliente',
        ),
        migrations.RenameField(
            model_name='roupa',
            old_name='idroupa',
            new_name='idRoupa',
        ),
        migrations.RenameField(
            model_name='roupa',
            old_name='nomebrecho',
            new_name='nomeBrecho',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='cliente_comprou',
            new_name='clienteComprou',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='DataVenda',
            new_name='dataVenda',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='idvenda',
            new_name='idVenda',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='roupa_comprada',
            new_name='roupaComprada',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='PrimeiroNome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='SegundoNome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nomeCliente',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
